#!/usr/bin/python3
'''check-lint: perform click lint checks'''
#
# Copyright (C) 2013 Canonical Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import print_function

import cr_common
import cr_lint
import optparse

if __name__ == "__main__":
    parser = optparse.OptionParser()
    parser.add_option("--output-json", dest="output_json",
                      action="store_true", default=False)
    (opt, args) = parser.parse_args()
    if len(args) < 1:
        cr_common.error("Must give path to click package")

    review = cr_lint.ClickReviewLint(args[0])
    if opt.output_json:
        review.click_report_output = "json"
    review.do_checks()
    review.print_report()
