#!/usr/bin/python3
'''collect-check-names-from-tests: print list of check names discovered from tests'''
#
# Copyright (C) 2015 Canonical Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import logging
import unittest

test_directory = 'clickreviews/tests/'

logging.basicConfig(level=logging.DEBUG)

suite = unittest.TestLoader().discover(test_directory)
unittest.TextTestRunner(verbosity=0).run(suite)
