#!/bin/sh
set -e

echo "= pep8 ="
for i in ./clickreviews/*py \
         ./clickreviews/tests/*py \
         ./bin/update-* \
         ./bin/click-check-* \
         ./bin/click-show-files \
         ./bin/click-review ; do
    if [ "$i" = "./clickreviews/tests/test_sr_declaration.py" -o \
         "$i" = "./clickreviews/tests/test_sr_security.py" ]; then
        # These file is hopelessly formatted against PEP8
        continue
    fi
    echo "Checking $i"
    pep8 $i
done
