#!/usr/bin/python3
'''check-skeleton: perform click skeleton checks'''
#
# Copyright (C) 2013 Canonical Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import print_function

import cr_common
import cr_lint
import os
import sys

# This script just dumps important files to stdout

if __name__ == "__main__":
    if len(sys.argv) < 2:
        cr_common.error("Must give path to click package")

    review = cr_lint.ClickReviewLint(sys.argv[1])

    for i in sorted(review.control_files):
        fh = cr_common.open_file_read(review.control_files[i])
        print("= %s =" % os.path.basename(i))
        for line in fh.readlines():
            print(line, end="")
        fh.close()
        print("")
