#!/usr/bin/python3

from clickreviews import cr_common
import os
import sys

if __name__ == '__main__':
    if len(sys.argv) != 3:
        cr_common.error("%s <clickpkg> <dir>" % os.path.basename(sys.argv[0]))

    pkg = sys.argv[1]
    dir = sys.argv[2]

    cr_common.unpack_click(pkg, dir)
    print("Successfully unpacked to '%s'" % dir)
